version: '3'
services:
  lakedrive-tests:
    profiles:
    - devel
    container_name: lakedrive-tests
    build:
      context: ../
      dockerfile: docker/tests/Dockerfile
    environment:
    - COVERAGE_FILE=/app/.cache/.coverage
    - PRE_COMMIT_HOME=/app/.cache

  minio-dev:
    profiles:
    - devel
    container_name: minio-dev
    build:
      context: minio
    environment:
    - MINIO_ROOT_USER=AKIAIOSFODNN7EXAMPLE
    - MINIO_ROOT_PASSWORD=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    - MINIO_SERVER_URL=https://minio-dev:8443
    command: [
      "server", "/mnt/minio-dev", "--certs-dir", "/.minio/certs",
      "--address", ":8443", "--console-address", ":9001"]
    ports:
    - 8443:8443
    - 9001:9001

  lakedrive-docs:
    profiles:
    - devel
    container_name: lakedrive-docs
    build:
      context: ../
      dockerfile: docker/docs/Dockerfile
    ports:
    - 8888:8888
